### ISSUE TITLE
 Sort ya icons out! 

### ISSUE THREAD

**Issue by kyleFirethought** [planetdecred/dcrandroid#185]
Hi @denyszayets , 

**Sort ya icons out!** (said in the deepest of scotish accents)

Also some slips on the colour scheme (**ticket.svg** and **walletAdd.svg** (hypothetical names here) are the wrong colour schemes and the **ticketVoted.svg** doesn't correlate with decrediton scheme) as well as a few icons that have landed in from the ether. 

What's wrong with **send.svg** and **document.svg** in dcrdesign(17 + 25)? - if there is, I need to know asap because I have a project including these two assets with completion imminent.  :( 

Also, believe there is a really nice **error.svg** and **checkmark.svg** included in dcrdesign iconset to which has been integrated into the notification system and also is a part of the **new stakepool themes** I believe. 

Anywho just some jump out observations. 👍 

Apart from that,  shaping up nicely. Looking forward to a mobile client. 💯 

-Kyle

**Comment by denyszayets** [comment]
@linnutee can you please share updated **error.svg** and **checkmark.svg**?

**Comment by raedah** [comment]
For the Play Store I need the following assets. Will need a set of these for the testnet wallet as well as for the mainnet wallet.

-Hi-res icon, 512 x 512, 32-bit PNG (with alpha)
-Feature graphic, 1024 w x 500 h, JPG or 24-bit PNG (no alpha)

We can also include screenshots of which I have several, but could be an area to include any other illustrations. JPEG or 24-bit PNG (no alpha). Min length for any side: 320px. Max length for any side: 3840px.

**Comment by denyszayets** [comment]
@raedah 512x512 
![512x512 2x](https://user-images.githubusercontent.com/33739891/47724485-28be4f80-dc2d-11e8-8e9d-fbb376b393a0.png)

**Comment by denyszayets** [comment]
Thanks @kyleFirethought I started implementing icon and color fixes two weeks ago.
Currently these changes and project is on hold.

@raedah please talk to Dustin on how and when to move forward. Thanks

**Comment by dreacot** [comment]
Resolved by https://github.com/planetdecred/dcrandroid/pull/401
