### ISSUE TITLE
disk space check and proper error

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrandroid#233]
A user reported an error of
"another process is using this Badger database"
and then later reported it was due to low disk space. We can check for this condition to properly alert the user.

**Comment by oregonisaac** [comment]
Bumping this up, this same error can also mean the program runs out of memory, and restarting the phone or force closing all applications may solve it.  Currently being reported on a phone with 4GB of space free.
![image](https://user-images.githubusercontent.com/4402603/52819483-41c50200-305e-11e9-94e9-5a64ae9583ee.png)
