### ISSUE TITLE
send page, tx byte sizes are non-intuitive to users

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrandroid#265]
When creating a transaction, the byte size of the transaction is shown, and it is valuable information since it relates to fee cost. General users may not understand how transactions are constructed and how the byte size is determined, or how it relates to the fee. Some further help information would be useful here, and anything that might make the process more intuitive for the user. To investigate.

**Comment by dreacot** [comment]
An info button could be added to educate users on what they are looking at @fegor_clinton
