### ISSUE TITLE
Wallet Crashes when trying to do a Send tx 

### ISSUE THREAD

**Issue by exitus1** [planetdecred/dcrandroid#465]
I was testing out the dcr android wallet and ran into issues where the wallet immediately crashed when inputting numbers on the send page! See screen capture: https://imgur.com/a/pUcLgYx

Edit: After closer inspection it appears the crash occurs only when I start the payment amount with a period.....so entering .1 for a payment doesn't work, but entering 0.1 works.

**Comment by C-ollins** [comment]
Error is [fixed](https://github.com/planetdecred/dcrandroid/pull/401) in latest release.
