### ISSUE TITLE
Time estimation error

### ISSUE THREAD

**Issue by degeri** [planetdecred/dcrandroid#486]
Replication.

-    let it sync normally and cancel halfway
-   continue sync

Note the time estimation.

The app states that the time left to sync is very low and only corrects itself after a long time.

From my understanding. Time estimation here seems to be based on previously completed work. So if 50% of the work was previously done then it will wrongly assume at time 10s (of new sync) that all the 50% of data was downloaded in the previous 10 seconds. So it calculates a very low "time remaining"

**Comment by C-ollins** [comment]
Fixed by https://github.com/planetdecred/dcrlibwallet/pull/143
`total headers in wallet/total headers to fetch` was being used instead of `total fetched headers/total headers to fetch`.
