### ISSUE TITLE
Bug: Can't send funds after receival to new wallet

### ISSUE THREAD

**Issue by svitekpavel** [planetdecred/dcrandroid#504]
I encountered a bug on Android -> 

**Steps to reproduce**
a) I open app, main screen, zero DCR in wallet
b) I receive tokens, I'm waiting for confirmations to go through
c) I open "Send screen". I can't send them to other address, because the Input field still shows "0.000000" Spendable tokens.

After I restart the app, I am able to spend/send the tokens.

**Version**: 2020-06-01
**Model**: Samsung Galaxy S10

**Comment by C-ollins** [comment]
Spending unconfirmed funds is disabled by default. You can enable ‘Spend unconfirmed funds’ in the app settings to be able to send funds without waiting for confirmation.

**Comment by dreacot** [comment]
Closing as this is the expected behaviour
