### ISSUE TITLE
Incorrect wallet spendable amount

### ISSUE THREAD

**Issue by dnldd** [planetdecred/dcrandroid#518]
I noticed my mobile wallet was reporting more value than I had that was spendable. On taking a closer look and comparing it to values reported by decrediton it looks like the mobile wallet is mistaking value locked by tickets as spendable. The locked by tickets value and spendable value are incorrect as a result.

**Comment by C-ollins** [comment]
Fixed in https://github.com/planetdecred/dcrlibwallet/pull/155

**Comment by dnldd** [comment]
Can confirm I'm on v1.5.2 and still having this issue.

**Comment by dnldd** [comment]
I had to rescan the wallet because a tx was failing from the mobile wallet. That also fixed the wallet value amounts. Perhaps the next release should automatically trigger a rescan on update to resolve such issues.

**Comment by C-ollins** [comment]
I'll look into the bug, it shouldn't need a rescan to work correctly.

**Comment by raedah** [comment]
@dnldd is this for android for ios?  Not clear which 'failing tx' condition you are referencing. If a tx doesnt propagate fully on the network, its quite possible a user would have to wait for a block to see the transaction. If its something else, its not clear what created out of sync balance for you. Its also not clear how the failing tx would be related to the locked balance you mentioned above, or if these are separate issues.

**Comment by dnldd** [comment]
It's for Android, while my wallet value totals were inccorect I tried sending a tx which stayed pending. Noticed it this morning so I rescan the wallet and tried again. That worked without issue, after which I noticed the wallet value totals had also corrected itself.

**Comment by raedah** [comment]
Did your pending tx go through after that?

**Comment by dnldd** [comment]
Nope I didn't see any error sending that transaction initially and the pending tx was removed after the rescan. I created another one and that was broadcasted as expected.

**Comment by dreacot** [comment]
Resolved in https://github.com/planetdecred/dcrlibwallet/pull/194
