### ISSUE TITLE
add usd equivalent balance to overview page

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrandroid#537]
A user should be able to see their DCR worth in USD, it makes it easier, rather than having to use 3rd party apps to calculate the USD equivalent

a detailed mockup can be seen here https://www.figma.com/file/BjhERfMRH1iDneygqSAksN/Total-USD-Overview

<img width="500" alt="Screen Shot 2021-03-19 at 15 35 37" src="https://user-images.githubusercontent.com/25265396/112333861-3e7bb600-8cbb-11eb-88ee-69aa3f20a444.png">

**Comment by C-ollins** [comment]
Closed by #539
