### ISSUE TITLE
Instructions how to verify releases

### ISSUE THREAD

**Issue by xaur** [planetdecred/dcrandroid#591]
Recent [v1.6.1 release](https://github.com/planetdecred/dcrandroid/releases/tag/v1.6.1) includes hashes and signatures to verify integrity and authenticity of APK downloads. But I don't know which key to verify the sigs against. Also, it would be good to promote sig verification to beginners by giving them the steps how to do it.

Projects like lnd add these instructions to [each release](https://github.com/lightningnetwork/lnd/releases). I think it is too verbose and blocks the ability to maintain these instructions in one place. I think a better way is to add verification instructions to project's README (or a separate document under `docs/`) and link that from each release (see [decred-binaries v1.6.3](https://github.com/decred/decred-binaries/releases/tag/v1.6.3) for an example).

**Comment by monsa00** [comment]
Hello,

Instructions have now been added to the release notes for both dcrandroid and godcr on how to verify the binaries using gpg.
