### ISSUE TITLE
Replace all instances of "seed phrase", "spending password" and "startup password" with 'seed words', 'spending passphrase', and 'startup passphrase'

### ISSUE THREAD

**Issue by Clariceco** [planetdecred/dcrandroid#594]
Find/Replace ALL instances of: "seed phrase" with 'seed words', 
Find/Replace All:  "spending password" with 'spending passphrase', and 
Find/Replace All: "startup password" with 'startup passphrase' @C-ollins @dreacot

**Comment by Fegor-Clinton** [comment]
This will also be useful to implement on the dcrandroid mockups.

**Comment by Fegor-Clinton** [comment]
This has been done and implemented for Godcr
