### ISSUE TITLE
Rework Sent DCR Page

### ISSUE THREAD

**Issue by monsa00** [planetdecred/dcrandroid#610]
Currently when DCR is sent the only indication is at the bottom of the drawer stating "Success" that slides up from the bottom with the transaction details. This is confusing because the page still shows that DCR *will be sent* instead of has already been sent. Perhaps the entire page should refresh to show *Transaction Details* instead of *Confirm to Send* once the transaction is initiated. 

Suggestions below:

![145727193-4274158f-7ac3-4976-a026-bbdbe5666d8f](https://user-images.githubusercontent.com/66281245/145838283-45985e92-6fce-4580-89d7-dd9d3f650bb5.png)

**Comment by yaroyazeed** [comment]
I will work on this.
