### ISSUE TITLE
Skip "Set up needed accounts" option screen for privacy if no additional accounts detected in wallet

### ISSUE THREAD

**Issue by monsa00** [planetdecred/dcrandroid#622]
Privacy setup currently allows the user to manually setup accounts even if the wallet has no additional accounts to map. This should be auto detected (the lack of accounts) and can infer the user has to setup new accounts if none exist.

![IMG_DC6DA18A516B-1](https://user-images.githubusercontent.com/66281245/160867510-dadadcc3-0598-4d3c-9a7f-182a353434e3.jpeg)

**Comment by yaroyazeed** [comment]
I will work on this.
