### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrandroid#7]
A dark theme that can be enabled in the settings.

**Comment by denyszayets** [comment]
Should we aim to design dark mode for revision 3.0?

**Comment by raedah** [comment]
I am open to it.

**Comment by raedah** [comment]
https://user-images.githubusercontent.com/39329216/42699658-0859c3e4-86df-11e8-9f77-22fa816b3c49.png

https://user-images.githubusercontent.com/39329216/42699652-07276cce-86df-11e8-860f-850930d52628.png

**Comment by dreacot** [comment]
Resolved by the following PRs https://github.com/planetdecred/dcrandroid/pull/572, #573, #574, #575, #577
